[package]
name = "macroquad-tiled-redux"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "^0.3.13"
tiled = "^0.9.5"

[patch.crates-io]
tiled = { path = "depends/rs-tiled" }
